version: "3.7"
services:
  app:
    image: ${IMAGE_REPO}${IMAGE_NAME:?err}:${IMAGE_TAG:?err}-dev
    build:
      context: .
      target: builder
    environment:
      WATCHPACK_POLLING: true
      NODE_ENV: development
    volumes:
      - ./app:/usr/src/next/app
      - ./public:/usr/src/next/public
      - ./next.config.js:/usr/src/next/next.config.js
      - ./tsconfig.json:/usr/src/next/tsconfig.json
      - ./tailwind.config.js:/usr/src/next/tailwind.config.js
  
  lambda:
    profiles:
      - "standalone"
    image: ${IMAGE_REPO}${IMAGE_NAME:?err}:${IMAGE_TAG:?err}-lambda
    platform: ${IMAGE_PLATFORM:-linux/arm64}
    build:
      context: .
      target: lambda
    env_file:
      - ./.env.local
    restart: on-failure:5
    ports:
      - 3001:3000